from . import airport_medical
from . import airport_medical_sex
from . import airport_medical_come
from . import airport_medical_comment
from . import airport_medical_nationality
from . import airport_medical_race
from . import airport_medical_company
from . import airport_medical_departure
from . import airport_medical_arrival
from . import airport_medical_incident_place
from . import airport_medical_incident_time
from . import airport_medical_chief_complaint
from . import airport_medical_diagnosis
from . import airport_medical_treatment
from . import airport_medical_result
from . import airport_medical_treatment_hospital
from . import airport_medical_attending_physician
from . import airport_medical_attending_nurse
from . import airport_medical_identity
from . import airport_medical_passing
from . import airport_medical_exit
from . import airport_medical_icd10_category
from . import airport_medical_icd10_category1
from . import airport_medical_icd10_category2
from . import airport_medical_icd10_category3
from . import airport_medical_icd10_category4
from . import airport_medical_icd10_category5
from . import airport_medical_icd10_category6
from . import airport_medical_icd10_category7
from . import airport_medical_icd10_category8
from . import airport_medical_icd10_category9
from . import airport_medical_icd10_category10
from . import airport_medical_icd10_category11
from . import airport_medical_icd10_category12
from . import airport_medical_icd10_category13
from . import airport_medical_icd10_category18
from . import airport_medical_icd10

